# Generated by Django 5.1.3 on 2024-11-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(verbose_name='Original Text')),
                ('source_language', models.CharField(max_length=50, verbose_name='Source Language')),
                ('translated_text', models.TextField(verbose_name='Translated Text')),
                ('target_language', models.CharField(max_length=50, verbose_name='Target Language')),
            ],
        ),
    ]
