# Generated by Django 5.1.3 on 2024-11-13 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_translation_created_at'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='users.customuser'),
            preserve_default=False,
        ),
    ]
